from allennlp.models.span_srl.propbank_semi_crf_srl import PropBankSemiCrfSrl
from allennlp.models.span_srl.frame_semi_crf_srl import FrameSemanticRoleLabeler
from allennlp.models.span_srl.scaffolding.scaffolded_frame_srl import ScaffoldedFrameSrl
